language: node_js
sudo: false
node_js:
  - "4"
  - "5"
script:
  - npm run linter
  - npm test
  - npm run test:cov
  - npm run test:cov:upload
notifications:
  slack: caffeinery:8dW6CO4XItYj4N5G9GTRbJeU
